# Generated by Django 5.1.3 on 2025-04-08 17:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
